### ISSUE TITLE
Version 0.3 is missing docs on hexdocs.pm

### ISSUE THREAD

**Issue by aquarhead** [ueberauth/ueberauth#29]
Both `Online Documentation` and the `docs` link of version 0.3.0 redirects to this: 

https://hexdocs.pm/ueberauth/README.md.html

which says "PAGE NOT FOUND".

**Comment by doomspork** [comment]
@aquarhead this is now fixed, thank you 👍

**Comment by aquarhead** [comment]
hmm... seems the link on hex.pm is still wrong.. I can download the docs, but when open it from my disk, it redirects to `file:///Users/aquarhead/Downloads/ueberauth-0.3.0/extra-api-reference.html` and not `/ueberauth/README.md.html`

It seems 0.2 version's `docs` link to a similar page as on my disk, but 0.3's link is wrong.

**Comment by doomspork** [comment]
@aquarhead I'm not sure if this is our issue or a caching issue with Hex.  The 0.3.0 doc link works: https://hexdocs.pm/ueberauth/0.3.0/extra-api-reference.html

**Comment by doomspork** [comment]
@hassox any ideas on this one?  I'm not particularly familiar with hexdocs
